nl:
  bsoft:
    apidemo:
      config:
        bestuurlijkegrenzen:
          rest:
            api:
              apikey: d379f340-6900-4b3c-9e10-b6a4296fdfca
              baseurl: https://brk.basisregistraties.overheid.nl/api/bestuurlijke-grenzen/v2
              coordinatereferencesystem: epsg:28992
              maxpagesize: 50

spring:
  application:
    name: '@project.name@'
  main:
    banner-mode: 'off'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ambtsgebied
    username: testuser
    password: 12345
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/ambtsgebied
    user: testuser
    password: 12345
    validateMigrationNaming: true
    locations: classpath:db/migration
  jpa:
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
        format_sql: true
        jdbc:
          batch_size: 100
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
